//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSVEntities : DbContext
    {
        public QLSVEntities()
            : base("name=QLSVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tblChucVu> tblChucVus { get; set; }
        public DbSet<tblDangNhap> tblDangNhaps { get; set; }
        public DbSet<tblDiem> tblDiems { get; set; }
        public DbSet<tblHocKy> tblHocKies { get; set; }
        public DbSet<tblHocPhan> tblHocPhans { get; set; }
        public DbSet<tblKhoa> tblKhoas { get; set; }
        public DbSet<tblKhoaHoc> tblKhoaHocs { get; set; }
        public DbSet<tblLopHanhChinh> tblLopHanhChinhs { get; set; }
        public DbSet<tblLopHocPhan> tblLopHocPhans { get; set; }
        public DbSet<tblNamHoc> tblNamHocs { get; set; }
        public DbSet<tblNganh> tblNganhs { get; set; }
        public DbSet<tblSinhVien> tblSinhViens { get; set; }
        public DbSet<tblSinhVien_ChucVu> tblSinhVien_ChucVu { get; set; }
        public DbSet<View_ChucVu> View_ChucVu { get; set; }
        public DbSet<View_Diem> View_Diem { get; set; }
        public DbSet<View_HocPhan> View_HocPhan { get; set; }
        public DbSet<View_KhoaHoc> View_KhoaHoc { get; set; }
        public DbSet<View_LopHanhChinh> View_LopHanhChinh { get; set; }
        public DbSet<View_LopHocPhan> View_LopHocPhan { get; set; }
        public DbSet<View_NamHoc> View_NamHoc { get; set; }
        public DbSet<View_Nganh> View_Nganh { get; set; }
        public DbSet<View_SinhVien> View_SinhVien { get; set; }
        public DbSet<View_TaiKhoan> View_TaiKhoan { get; set; }
    }
}
