//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChucVu
    {
        public tblChucVu()
        {
            this.tblSinhVien_ChucVu = new HashSet<tblSinhVien_ChucVu>();
        }
    
        public int CV_ID { get; set; }
        public string CV_TenChucVu { get; set; }
    
        public virtual ICollection<tblSinhVien_ChucVu> tblSinhVien_ChucVu { get; set; }
    }
}
