//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDangNhap
    {
        public int TK_ID { get; set; }
        public string TK_TenDangNhap { get; set; }
        public string TK_MatKhau { get; set; }
        public string TK_QuyenHan { get; set; }
        public Nullable<int> SV_ID { get; set; }
    
        public virtual tblSinhVien tblSinhVien { get; set; }
    }
}
