//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiem
    {
        public int DIEM_ID { get; set; }
        public Nullable<int> SV_ID { get; set; }
        public Nullable<int> LHP_ID { get; set; }
        public Nullable<double> DIEM_ChuyenCan { get; set; }
        public Nullable<double> DIEM_GiuaKy { get; set; }
        public Nullable<double> DIEM_CuoiKy { get; set; }
        public Nullable<double> DIEM_TongKet { get; set; }
    
        public virtual tblLopHocPhan tblLopHocPhan { get; set; }
        public virtual tblSinhVien tblSinhVien { get; set; }
    }
}
