//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHocPhan
    {
        public tblHocPhan()
        {
            this.tblLopHocPhans = new HashSet<tblLopHocPhan>();
        }
    
        public int HP_ID { get; set; }
        public string HP_TenHocPhan { get; set; }
        public Nullable<int> HP_SoTinChi { get; set; }
        public Nullable<int> HP_SoTietLyThuyet { get; set; }
        public Nullable<int> HP_SoTietThucHanh { get; set; }
        public string HP_MoTa { get; set; }
        public Nullable<int> NG_ID { get; set; }
    
        public virtual tblNganh tblNganh { get; set; }
        public virtual ICollection<tblLopHocPhan> tblLopHocPhans { get; set; }
    }
}
