//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhoa
    {
        public tblKhoa()
        {
            this.tblNganhs = new HashSet<tblNganh>();
        }
    
        public int K_ID { get; set; }
        public string K_TenKhoa { get; set; }
        public string K_TenTruongKhoa { get; set; }
        public string K_DiaChi { get; set; }
        public string K_DienThoai { get; set; }
        public string K_Email { get; set; }
    
        public virtual ICollection<tblNganh> tblNganhs { get; set; }
    }
}
