//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLopHocPhan
    {
        public tblLopHocPhan()
        {
            this.tblDiems = new HashSet<tblDiem>();
        }
    
        public int LHP_ID { get; set; }
        public Nullable<int> HP_ID { get; set; }
        public string LHP_TenLopHP { get; set; }
        public string LHP_GiangVien { get; set; }
        public Nullable<int> NH_ID { get; set; }
        public Nullable<int> HK_ID { get; set; }
        public string LHP_PhongHoc { get; set; }
        public Nullable<System.DateTime> LHP_NgayBatDau { get; set; }
        public Nullable<System.DateTime> LHP_NgayKetThuc { get; set; }
    
        public virtual ICollection<tblDiem> tblDiems { get; set; }
        public virtual tblHocKy tblHocKy { get; set; }
        public virtual tblHocPhan tblHocPhan { get; set; }
        public virtual tblNamHoc tblNamHoc { get; set; }
    }
}
