//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLopHanhChinh
    {
        public tblLopHanhChinh()
        {
            this.tblSinhViens = new HashSet<tblSinhVien>();
        }
    
        public int LP_ID { get; set; }
        public string LP_TenLop { get; set; }
        public string LP_TenChuNhiem { get; set; }
        public Nullable<int> NG_ID { get; set; }
    
        public virtual tblNganh tblNganh { get; set; }
        public virtual ICollection<tblSinhVien> tblSinhViens { get; set; }
    }
}
