//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNganh
    {
        public tblNganh()
        {
            this.tblHocPhans = new HashSet<tblHocPhan>();
            this.tblLopHanhChinhs = new HashSet<tblLopHanhChinh>();
        }
    
        public int NG_ID { get; set; }
        public string NG_TenNganh { get; set; }
        public string NG_SoTinChi { get; set; }
        public string NG_MoTa { get; set; }
        public Nullable<int> K_ID { get; set; }
    
        public virtual ICollection<tblHocPhan> tblHocPhans { get; set; }
        public virtual tblKhoa tblKhoa { get; set; }
        public virtual ICollection<tblLopHanhChinh> tblLopHanhChinhs { get; set; }
    }
}
