//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNamHoc
    {
        public tblNamHoc()
        {
            this.tblLopHocPhans = new HashSet<tblLopHocPhan>();
        }
    
        public int NH_ID { get; set; }
        public string NH_TenNamHoc { get; set; }
        public string NH_MoTa { get; set; }
    
        public virtual ICollection<tblLopHocPhan> tblLopHocPhans { get; set; }
    }
}
