//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSinhVien
    {
        public tblSinhVien()
        {
            this.tblDangNhaps = new HashSet<tblDangNhap>();
            this.tblDiems = new HashSet<tblDiem>();
            this.tblSinhVien_ChucVu = new HashSet<tblSinhVien_ChucVu>();
        }
    
        public int SV_ID { get; set; }
        public string SV_MaSV { get; set; }
        public string SV_HoVaTen { get; set; }
        public Nullable<System.DateTime> SV_NgaySinh { get; set; }
        public string SV_GioiTinh { get; set; }
        public string SV_DiaChi { get; set; }
        public string SV_Email { get; set; }
        public string SV_DienThoai { get; set; }
        public Nullable<int> LP_ID { get; set; }
        public Nullable<int> KH_ID { get; set; }
    
        public virtual ICollection<tblDangNhap> tblDangNhaps { get; set; }
        public virtual ICollection<tblDiem> tblDiems { get; set; }
        public virtual tblKhoaHoc tblKhoaHoc { get; set; }
        public virtual tblLopHanhChinh tblLopHanhChinh { get; set; }
        public virtual ICollection<tblSinhVien_ChucVu> tblSinhVien_ChucVu { get; set; }
    }
}
