//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LopHocPhan
    {
        public int id { get; set; }
        public string HP_TenHocPhan { get; set; }
        public string LHP_TenLopHP { get; set; }
        public string SV_HoVaTen { get; set; }
        public string LHP_GiangVien { get; set; }
        public string LHP_PhongHoc { get; set; }
        public Nullable<System.DateTime> LHP_NgayBatDau { get; set; }
        public Nullable<System.DateTime> LHP_NgayKetThuc { get; set; }
        public string HK_TenHocKy { get; set; }
        public string NH_TenNamHoc { get; set; }
    }
}
