//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Nganh
    {
        public int id { get; set; }
        public string K_TenKhoa { get; set; }
        public string NG_TenNganh { get; set; }
        public string NG_SoTinChi { get; set; }
        public string NG_MoTa { get; set; }
    }
}
