//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ChucVu
    {
        public int SVCV_ID { get; set; }
        public string SV_HoVaTen { get; set; }
        public string CV_TenChucVu { get; set; }
    }
}
