//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SinhVien
    {
        public int id { get; set; }
        public string K_TenKhoa { get; set; }
        public string NG_TenNganh { get; set; }
        public string LP_TenLop { get; set; }
        public string KH_TenKhoaHoc { get; set; }
        public string SV_MaSV { get; set; }
        public string SV_HoVaTen { get; set; }
        public Nullable<System.DateTime> SV_NgaySinh { get; set; }
        public string SV_GioiTinh { get; set; }
        public string SV_DiaChi { get; set; }
        public string SV_Email { get; set; }
        public string SV_DienThoai { get; set; }
        public string CV_TenChucVu { get; set; }
    }
}
