//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_KhoaHoc
    {
        public int id { get; set; }
        public string KH_TenKhoaHoc { get; set; }
        public string SV_HoVaTen { get; set; }
        public Nullable<int> KH_NamBatDau { get; set; }
        public Nullable<int> KH_NamKetThuc { get; set; }
    }
}
