//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Diem
    {
        public int id { get; set; }
        public string HK_TenHocKy { get; set; }
        public string LHP_TenLopHP { get; set; }
        public string SV_HoVaTen { get; set; }
        public Nullable<double> DIEM_ChuyenCan { get; set; }
        public Nullable<double> DIEM_GiuaKy { get; set; }
        public Nullable<double> DIEM_CuoiKy { get; set; }
        public Nullable<double> DIEM_TongKet { get; set; }
    }
}
