//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_NamHoc
    {
        public int id { get; set; }
        public string LHP_TenLopHP { get; set; }
        public string NH_TenNamHoc { get; set; }
        public string NH_MoTa { get; set; }
    }
}
